eureka:
  instance:
    prefer-ip-address: true

  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://35.154.182.218:8761/eureka
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  # Auto-detect services registered in Eureka
          lower-case-service-id: true

      routes:
        - id: AUTH-SERVICE
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth/**
          filters:
              -name: AuthFilter
        #          filters:
#            - StripPrefix=1
        - id: NOTIFICATION-SERVICE
          uri: lb://NOTIFICATION-SERVICE
          predicates:
            - Path=/notification/**
#          filters:
#            - StripPrefix=1
#            - name: AuthFilter
        - id: INVENTORY-SERVICE
          uri: lb://INVENTORY-SERVICE
          predicates:
            - Path=/inventory/**
          filters:
            - name: AuthFilter


logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.cloud.gateway.filter: TRACE
    org.springframework.web.reactive: DEBUG
